/**
 * Latest global models (2025–2026). Extend this list for 2027+ without schema changes.
 * One entry = one unique listing (brand + model + year).
 */
export const NEW_GLOBAL_CARS = [
  { brand: 'Toyota', model: 'Camry', year: 2026, body: 'Sedan', fuel: 'Hybrid', engine: '2.5L Hybrid', power: 225, price: 32000, trans: 'Automatic' },
  { brand: 'Toyota', model: 'RAV4', year: 2026, body: 'SUV', fuel: 'Hybrid', engine: '2.5L Hybrid', power: 219, price: 34000, trans: 'Automatic' },
  { brand: 'Toyota', model: 'Land Cruiser', year: 2025, body: 'SUV', fuel: 'Petrol', engine: '3.5L V6', power: 409, price: 72000, trans: 'Automatic' },
  { brand: 'BMW', model: '5 Series', year: 2026, body: 'Sedan', fuel: 'Hybrid', engine: '2.0L PHEV', power: 295, price: 62000, trans: 'Automatic' },
  { brand: 'BMW', model: 'X5', year: 2026, body: 'SUV', fuel: 'Petrol', engine: '3.0L', power: 375, price: 71000, trans: 'Automatic' },
  { brand: 'BMW', model: 'i4', year: 2025, body: 'Sedan', fuel: 'Electric', engine: 'Electric', power: 335, price: 58000, trans: 'Automatic' },
  { brand: 'Mercedes-Benz', model: 'E-Class', year: 2026, body: 'Sedan', fuel: 'Hybrid', engine: '2.0L Hybrid', power: 375, price: 68000, trans: 'Automatic' },
  { brand: 'Mercedes-Benz', model: 'GLE', year: 2025, body: 'SUV', fuel: 'Petrol', engine: '3.0L', power: 375, price: 74000, trans: 'Automatic' },
  { brand: 'Mercedes-Benz', model: 'EQE', year: 2025, body: 'Sedan', fuel: 'Electric', engine: 'Electric', power: 288, price: 76000, trans: 'Automatic' },
  { brand: 'Audi', model: 'A6', year: 2026, body: 'Sedan', fuel: 'Petrol', engine: '2.0L TFSI', power: 261, price: 59000, trans: 'Automatic' },
  { brand: 'Audi', model: 'Q7', year: 2025, body: 'SUV', fuel: 'Petrol', engine: '3.0L', power: 335, price: 69000, trans: 'Automatic' },
  { brand: 'Audi', model: 'Q6 e-tron', year: 2025, body: 'SUV', fuel: 'Electric', engine: 'Electric', power: 382, price: 72000, trans: 'Automatic' },
  { brand: 'Lexus', model: 'RX', year: 2026, body: 'SUV', fuel: 'Hybrid', engine: '2.5L Hybrid', power: 275, price: 56000, trans: 'Automatic' },
  { brand: 'Lexus', model: 'ES', year: 2025, body: 'Sedan', fuel: 'Hybrid', engine: '2.5L Hybrid', power: 215, price: 48000, trans: 'Automatic' },
  { brand: 'Lexus', model: 'NX', year: 2026, body: 'SUV', fuel: 'Hybrid', engine: '2.5L Hybrid', power: 239, price: 47000, trans: 'Automatic' },
  { brand: 'Porsche', model: 'Macan Electric', year: 2025, body: 'SUV', fuel: 'Electric', engine: 'Electric', power: 402, price: 82000, trans: 'Automatic' },
  { brand: 'Porsche', model: '911', year: 2026, body: 'Sports', fuel: 'Petrol', engine: '3.0L Twin-Turbo', power: 379, price: 128000, trans: 'Automatic' },
  { brand: 'Porsche', model: 'Cayenne', year: 2025, body: 'SUV', fuel: 'Petrol', engine: '3.0L', power: 348, price: 89000, trans: 'Automatic' },
  { brand: 'Tesla', model: 'Model 3', year: 2026, body: 'Sedan', fuel: 'Electric', engine: 'Electric', power: 283, price: 42000, trans: 'Automatic' },
  { brand: 'Tesla', model: 'Model Y', year: 2026, body: 'SUV', fuel: 'Electric', engine: 'Electric', power: 295, price: 48000, trans: 'Automatic' },
  { brand: 'Tesla', model: 'Model S', year: 2025, body: 'Sedan', fuel: 'Electric', engine: 'Electric', power: 670, price: 92000, trans: 'Automatic' },
  { brand: 'Ford', model: 'Mustang', year: 2025, body: 'Sports', fuel: 'Petrol', engine: '5.0L V8', power: 480, price: 45000, trans: 'Manual' },
  { brand: 'Ford', model: 'Explorer', year: 2026, body: 'SUV', fuel: 'Hybrid', engine: '2.3L Hybrid', power: 318, price: 46000, trans: 'Automatic' },
  { brand: 'Ford', model: 'F-150 Lightning', year: 2025, body: 'Pickup', fuel: 'Electric', engine: 'Electric', power: 580, price: 62000, trans: 'Automatic' },
  { brand: 'Chevrolet', model: 'Equinox EV', year: 2025, body: 'SUV', fuel: 'Electric', engine: 'Electric', power: 213, price: 36000, trans: 'Automatic' },
  { brand: 'Chevrolet', model: 'Silverado', year: 2026, body: 'Pickup', fuel: 'Petrol', engine: '5.3L V8', power: 355, price: 48000, trans: 'Automatic' },
  { brand: 'Hyundai', model: 'Tucson', year: 2026, body: 'SUV', fuel: 'Hybrid', engine: '1.6L Hybrid', power: 231, price: 34000, trans: 'Automatic' },
  { brand: 'Hyundai', model: 'Ioniq 5', year: 2025, body: 'SUV', fuel: 'Electric', engine: 'Electric', power: 320, price: 44000, trans: 'Automatic' },
  { brand: 'Hyundai', model: 'Sonata', year: 2025, body: 'Sedan', fuel: 'Hybrid', engine: '2.0L Hybrid', power: 192, price: 30000, trans: 'Automatic' },
  { brand: 'Kia', model: 'Sportage', year: 2026, body: 'SUV', fuel: 'Hybrid', engine: '1.6L Hybrid', power: 227, price: 33000, trans: 'Automatic' },
  { brand: 'Kia', model: 'EV6', year: 2025, body: 'SUV', fuel: 'Electric', engine: 'Electric', power: 320, price: 46000, trans: 'Automatic' },
  { brand: 'Kia', model: 'K5', year: 2025, body: 'Sedan', fuel: 'Petrol', engine: '1.6L Turbo', power: 180, price: 28000, trans: 'Automatic' },
  { brand: 'Volkswagen', model: 'Tiguan', year: 2026, body: 'SUV', fuel: 'Petrol', engine: '2.0L TSI', power: 201, price: 36000, trans: 'Automatic' },
  { brand: 'Volkswagen', model: 'ID.4', year: 2025, body: 'SUV', fuel: 'Electric', engine: 'Electric', power: 201, price: 42000, trans: 'Automatic' },
  { brand: 'Volkswagen', model: 'Golf', year: 2025, body: 'Hatchback', fuel: 'Petrol', engine: '1.5L TSI', power: 150, price: 29000, trans: 'Automatic' },
  { brand: 'Nissan', model: 'Patrol', year: 2025, body: 'SUV', fuel: 'Petrol', engine: '3.5L Twin-Turbo', power: 425, price: 78000, trans: 'Automatic' },
  { brand: 'Nissan', model: 'Ariya', year: 2025, body: 'SUV', fuel: 'Electric', engine: 'Electric', power: 238, price: 45000, trans: 'Automatic' },
  { brand: 'Honda', model: 'CR-V', year: 2026, body: 'SUV', fuel: 'Hybrid', engine: '2.0L Hybrid', power: 204, price: 36000, trans: 'Automatic' },
  { brand: 'Honda', model: 'Accord', year: 2025, body: 'Sedan', fuel: 'Hybrid', engine: '2.0L Hybrid', power: 204, price: 34000, trans: 'Automatic' },
  { brand: 'Volvo', model: 'XC90', year: 2026, body: 'SUV', fuel: 'Hybrid', engine: '2.0L PHEV', power: 455, price: 72000, trans: 'Automatic' },
  { brand: 'Volvo', model: 'EX30', year: 2025, body: 'SUV', fuel: 'Electric', engine: 'Electric', power: 268, price: 38000, trans: 'Automatic' },
  { brand: 'BYD', model: 'Seal', year: 2026, body: 'Sedan', fuel: 'Electric', engine: 'Electric', power: 308, price: 36000, trans: 'Automatic' },
  { brand: 'BYD', model: 'Song Plus', year: 2025, body: 'SUV', fuel: 'Hybrid', engine: '1.5L DM-i', power: 197, price: 32000, trans: 'Automatic' },
  { brand: 'BYD', model: 'Han', year: 2025, body: 'Sedan', fuel: 'Electric', engine: 'Electric', power: 517, price: 48000, trans: 'Automatic' },
  { brand: 'BYD', model: 'Yuan Plus', year: 2025, body: 'SUV', fuel: 'Electric', engine: 'Electric', power: 204, price: 30000, trans: 'Automatic' },
  { brand: 'Chery', model: 'Arrizo 8', year: 2025, body: 'Sedan', fuel: 'Petrol', engine: '1.6L Turbo', power: 197, price: 26000, trans: 'Automatic' },
  { brand: 'Chery', model: 'Tiggo 8', year: 2026, body: 'SUV', fuel: 'Petrol', engine: '2.0L Turbo', power: 254, price: 32000, trans: 'Automatic' },
  { brand: 'Haval', model: 'Jolion', year: 2025, body: 'SUV', fuel: 'Petrol', engine: '1.5L Turbo', power: 150, price: 24000, trans: 'Automatic' },
  { brand: 'Geely', model: 'Monjaro', year: 2025, body: 'SUV', fuel: 'Petrol', engine: '2.0L Turbo', power: 238, price: 34000, trans: 'Automatic' },
  { brand: 'Land Rover', model: 'Range Rover Sport', year: 2025, body: 'SUV', fuel: 'Petrol', engine: '3.0L', power: 395, price: 95000, trans: 'Automatic' },
  { brand: 'Land Rover', model: 'Defender', year: 2026, body: 'SUV', fuel: 'Petrol', engine: '3.0L', power: 395, price: 88000, trans: 'Automatic' },
  { brand: 'Ferrari', model: 'Roma Spider', year: 2025, body: 'Sports', fuel: 'Petrol', engine: '3.9L V8', power: 612, price: 280000, trans: 'Automatic' },
  { brand: 'Lamborghini', model: 'Temerario', year: 2026, body: 'Sports', fuel: 'Hybrid', engine: '4.0L V8 Hybrid', power: 907, price: 390000, trans: 'Automatic' },
  { brand: 'Jaguar', model: 'F-Pace', year: 2025, body: 'SUV', fuel: 'Petrol', engine: '2.0L', power: 247, price: 58000, trans: 'Automatic' },
  { brand: 'Mazda', model: 'CX-60', year: 2025, body: 'SUV', fuel: 'Hybrid', engine: '2.5L PHEV', power: 323, price: 48000, trans: 'Automatic' },
  { brand: 'Subaru', model: 'Forester', year: 2026, body: 'SUV', fuel: 'Petrol', engine: '2.5L', power: 180, price: 34000, trans: 'Automatic' },
  { brand: 'Jeep', model: 'Grand Cherokee', year: 2025, body: 'SUV', fuel: 'Petrol', engine: '3.6L', power: 293, price: 46000, trans: 'Automatic' },
  { brand: 'Genesis', model: 'GV70', year: 2025, body: 'SUV', fuel: 'Petrol', engine: '2.5L Turbo', power: 300, price: 52000, trans: 'Automatic' },
  { brand: 'Genesis', model: 'Electrified G80', year: 2025, body: 'Sedan', fuel: 'Electric', engine: 'Electric', power: 365, price: 74000, trans: 'Automatic' },
];
